### PR TITLE
Use PowerShell instead of bat script

### PR DESCRIPTION
**Pull request by mjenczmyk**
Honestly I'm not sure if this will work - if you have a better idea how to do this scripting in PowerShell feel free to propose changes, I couldn't even test if it's working (the entire pull request is based on what I've read about PowerShell on the internet).

### CODE REVIEW

**Comment by igbt6** [comment]
I will test it and then merge

**Comment by igbt6** [comment]
Actually i already lost my last machine with Windows, so I will not test it : (

**Comment by mjenczmyk** [comment]
Can somebody check whether it works and fix possible errors? Neither me nor @igbt6 have access to machine with Windows.

**Comment by mjenczmyk** [comment]
Made obsolete by #111.

**Pull request closed without merging**
